// prisma/seed.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.user.createMany({
    data: [
      {
        id: 1,
        name: "Rahul Patil",
        email: "rahul.patil@example.com",
        password: "$2b$10$hashedpassword1",
        phone: "+91-9876543210",
        role: "FARMER",
        latitude: 18.5204,
        longitude: 73.8567,
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 2,
        name: "Anjali Sharma",
        email: "anjali.sharma@example.com",
        password: "$2b$10$hashedpassword2",
        phone: "+91-9123456780",
        role: "CUSTOMER",
        latitude: 28.6139,
        longitude: 77.209,
        city: "Delhi",
        state: "Delhi",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 3,
        name: "Ravi Kumar",
        email: "ravi.kumar@example.com",
        password: "$2b$10$hashedpassword3",
        phone: "+91-9988776655",
        role: "FARMER",
        latitude: 26.9124,
        longitude: 75.7873,
        city: "Jaipur",
        state: "Rajasthan",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 4,
        name: "Sonia Gupta",
        email: "sonia.gupta@example.com",
        password: "$2b$10$hashedpassword4",
        phone: "+91-9001122334",
        role: "CUSTOMER",
        latitude: 19.076,
        longitude: 72.8777,
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 5,
        name: "Amit Joshi",
        email: "amit.joshi@example.com",
        password: "$2b$10$hashedpassword5",
        phone: "+91-9456781234",
        role: "FARMER",
        latitude: 12.9716,
        longitude: 77.5946,
        city: "Bangalore",
        state: "Karnataka",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 6,
        name: "Priya Nair",
        email: "priya.nair@example.com",
        password: "$2b$10$hashedpassword6",
        phone: "+91-9765432100",
        role: "CUSTOMER",
        latitude: 13.0827,
        longitude: 80.2707,
        city: "Chennai",
        state: "Tamil Nadu",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 7,
        name: "Deepak Singh",
        email: "deepak.singh@example.com",
        password: "$2b$10$hashedpassword7",
        phone: "+91-9876549876",
        role: "FARMER",
        latitude: 23.2599,
        longitude: 77.4126,
        city: "Bhopal",
        state: "Madhya Pradesh",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 8,
        name: "Meera Das",
        email: "meera.das@example.com",
        password: "$2b$10$hashedpassword8",
        phone: "+91-9988998877",
        role: "CUSTOMER",
        latitude: 22.5726,
        longitude: 88.3639,
        city: "Kolkata",
        state: "West Bengal",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 9,
        name: "Karan Verma",
        email: "karan.verma@example.com",
        password: "$2b$10$hashedpassword9",
        phone: "+91-9090909090",
        role: "FARMER",
        latitude: 17.385,
        longitude: 78.4867,
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        createdAt: new Date(),
      },
      {
        id: 10,
        name: "Sneha Kapoor",
        email: "sneha.kapoor@example.com",
        password: "$2b$10$hashedpassword10",
        phone: "+91-9887766554",
        role: "CUSTOMER",
        latitude: 15.2993,
        longitude: 74.124,
        city: "Panaji",
        state: "Goa",
        country: "India",
        createdAt: new Date(),
      },
    ],
  });
  console.log("✅ Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
